role_play:
    post:
        reward:
            point_multiplier: 1 
            min_word_count: 50
            max_word_count: 550
            monetary:
                gold: 0
                platin: 0.1
                gems: 1
                word_count: 5.5
        word_filter: false
    colored_name:
        price:
            gold: 0
            platin: 0
            gems: 200
    colored_title:
        price:
            gold: 0
            platin: 0
            gems: 500
    stat_reset: #Preis um die Stats eines Charakters zurück zu setzen
        price:
            gold: 0
            platin: 0
            gems: 500
    bulletin:
        price:
            gold: 100
            platin: 0
            gems: 0
         
house:
    price:
        gold: 0
        platin: 100
        gems: 350
    room:
        price: #Wenn die Stufe eines Hauses erweitert wird, gilt dieser Preis
            gold: 0
            platin: 150
            gems: 0
    intrusion_chance: 12 #1d20 Standardchance, dass ein Einbruch fehlschlägt
    house_area: 10
    nav_update:
        price: #Wenn die Orte neu angeordnet werden, muss dies bezahlt werden
            gold: 0
            platin: 150
            gems: 0
    key:
        key_per_room: 1 #Die Anzahl Schlüssel, die man pro Raum um sonst verteilen kann
        price:
            gold: 1000
            platin: 150
            gems: 0
    levels:
        1: Verschlag
        4: Bruchbude
        5: Laube
        7: Hütte
        9: Holzhäuschen
        11: Häuschen
        14: Haus
        17: Villa
        21: Anwesen
        26: Residenz
    max_rooms: 26 #Ab dieser Stufe kostet jeder Raum soviel wie ein neues Haus
            
guild:
    founding_price:
            gold: 0
            platin: 1000
            gems: 0
            
settings:
    start_money:
        gold: 0
        platin: 0
        gems: 0
    start_user_level: 1
    action_points: 50
    email_validation: 0
    phase_per_day: 4
    ooc_days: 3
    post_days: 28
    delete_threshold: 365
    
            
            
        